### ISSUE TITLE
No ethernet

### ISSUE THREAD

**Issue by Miouyouyou** [Miouyouyou/RockMyy64#1]
It seems to be due to not defining a "regulator" in the DTS node.

```
[   13.483273] rk_gmac-dwmac fe300000.ethernet: PTP uses main clock
[   13.483345] rk_gmac-dwmac fe300000.ethernet: no regulator found
[   13.484047] rk_gmac-dwmac fe300000.ethernet: clock input or output? (input).
[   13.484072] rk_gmac-dwmac fe300000.ethernet: TX delay(0x28).
[   13.484087] rk_gmac-dwmac fe300000.ethernet: RX delay(0x11).
[   13.484111] rk_gmac-dwmac fe300000.ethernet: integrated PHY? (no).
[   13.484185] rk_gmac-dwmac fe300000.ethernet: clock input from PHY
[   13.489250] rk_gmac-dwmac fe300000.ethernet: init for RGMII
[   13.489284] rk_gmac-dwmac fe300000.ethernet: no regulator found
[   13.501244] rk_gmac-dwmac: probe of fe300000.ethernet failed with error -1
```

**Comment by npcomplete13** [comment]
take a look here:

https://github.com/ayufan-rock64/linux-kernel/blob/release-4.4/arch/arm64/boot/dts/rockchip/rk3399-rockpro64.dts

**Comment by Miouyouyou** [comment]
Thanks for the link. I'll take a look this week-end.

**Comment by Miouyouyou** [comment]
Okay, I took a look at that, but I guess that it will need a few tweaks here and there to port it to mainline kernels. I'll try to focus on this next week.

Since I forgot to copy the configuration I did previously, I have to redo the configuration part of the kernel, which will easily take a few hours to (re)test.

**Comment by npcomplete13** [comment]
His mainline is here: https://github.com/ayufan-rock64/linux-mainline-kernel
