### ISSUE TITLE
v5.6 VPU patches break the boot process

### ISSUE THREAD

**Issue by Miouyouyou** [Miouyouyou/RockMyy64#4]
No idea why though.

**Comment by rubenvb** [comment]
If you switched between 4.x and 5.X kernels at the same time, the disk device enumeration might have changed. I use `root=/dev/mmcblk2p2` for my rootfs on eMMC.

**Comment by Miouyouyou** [comment]
Ah, close, actually it was the UUID= that suddenly broke. The kernel wasn't able to find the right partition and "got stuck", without clear warning.

Anyway, the problem is solved, I'll update the repository in a few minutes.
